### ISSUE TITLE
Unwanted word extenders on tied notes

### ISSUE THREAD

**Issue by jgwcouk** [fkretlow/figurato#2]
Loving this project - simple to use and great results - thank you!

I've set up the _Lyric Translation_ text style to adopt **Figurato** and it works well, but I've been wrestling with how to get rid of word extenders (the underscores) when a figure is placed on a tied note. I can't see workaround that doesn't involve manual edits in Engrave mode, which seems to go against the whole **Dorico** philosophy. If the project contains proper lyrics elsewhere where those extenders are required so can't be suppressed globally (not that I have found a  way to do that either!). Any suggestions? Hopefully, **Dorico** devs will adopt this idea and create a special lyric type for figures one day!

**Comment by fkretlow** [comment]
I’m glad you find the font useful!

If you don’t need real lyrics in the same project you can turn off extender lines by setting their minimum length to something absurdly high, like 50 spaces, on the Lyrics page of Engraving Options.

If you do need real lyrics, well… you can either

- untie the notes, enter the figures and tie the notes again, or  
- make all the manual edits at once after you've entered all the figures: select the whole basso continuo staff, filter lyrics, with this selection switch to Engrave Mode, activate either the Line Start X or the Line End X property in the properties panel and input an absurdly high (or low for Line End X) value like 50/–50 spaces.

Tieing and untieing is also the way to go when you need more than one figure below a tie chain.

I hope that helps!

**Comment by jgwcouk** [comment]
Thanks Florian. Very helpful tips indeed.

Incidentally, have you found a way of dealing with suspensions when, for example, you might want two or more different figures on the separate crotchet beats making up a minim or semibreve? I’ve discovered that by adding a voice of crotchets to attach the figures to and then deleting the voice the figures persist, but I’ve not found a way of achieving this without such a workaround, though copy and paste is helpful once you’ve done one bar. What I have noticed, though, is that the beat spacing is uneven – see the second bar of this sample:

[cid:image001.jpg@01D44D96.C2F471E0]
John

**Comment by fkretlow** [comment]
John, I can't see the picture, but I think you want to achieve something like in the example on the landing page of the repository on the third beat of the second and third measure, right?  
If so, you need to use some sort of a workaround, yes. Using a second voice is possible. You could also enter a note on each rhythmic position where you need a figure and merge all the notes later by simply tieing them. Or you could advance the caret to the desired rhythmic position and invoke the lyrics popover there.
Either way, I'm afraid you'll have to do some manual adjustments in Engrave Mode, perhaps allow more horizontal space for the figures and certainly nudge the figures around until they look evenly spaced.

**Comment by jgwcouk** [comment]
Thanks for the advice - will experiment some more!
