### ISSUE TITLE
figured bass continuation line as in Walter Piston's book 'Harmony' (ex pg 315)

### ISSUE THREAD

**Issue by tbabcock123** [fkretlow/figurato#5]
is it possible in the current implementation of Figurato to have a continuation line as used by Walter Piston in his 'Harmony' text, to indicate that the note specified by the figure continues through the changing harmony indicated by the bass?  example attached.
<img width="492" alt="Screen Shot 2020-04-25 at 8 54 08 AM" src="https://user-images.githubusercontent.com/64321808/80284558-30e93500-86d4-11ea-8ec4-c3d1cea43695.png">

**Comment by fkretlow** [comment]
Not really. As shown in the manual you can build continuation lines with Em dashes, but that's far too cumbersome and awkward if you need many of them.

I'm afraid that's a limitation of handling the positioning in the font itself. Drawing arbitrarily long lines is simply outside the scope of font technology.

**Comment by tbabcock123** [comment]
thanks.  I found a workaround (using the hyphen).  there are some situations that are more problematic but I'll work out something.  since any future implementation of figured bass in Dorico might involve fonts, it looks like this problem won't go away.  I'm not a figured bass expert and only following the exercises given by Piston in his book, but are the figured bass symbols as shown in the screenshot I sent standard?

**Comment by fkretlow** [comment]
No, any notation software is capable of drawing primitive lines when needed. Once Dorico has its own implementation of figured bass, all this becomes moot.

Yes, those figures (and indeed continuation lines) are very common.
