### ISSUE TITLE
7532 stack

### ISSUE THREAD

**Issue by philipmayr** [fkretlow/figurato#8]

**Comment by fkretlow** [comment]
Hi Philip, apologies for the late reply. The font supports up to five layers of figures, so what you're asking for should be possible. Does it not work for you, and if so, in what environment/software are you experiencing the issue?

**Comment by philipmayr** [comment]
All good, thanks for the reply. The 7532 stack doesn't seem to come together on Pages, TextEdit, and XCode on macOS- I'll check on Windows in a bit. When I try to put a 2 below the 753, the 2 jumps over to the head of the next column. Other 4 figure stacks such as 8753 display all right. Maybe I'm just missing a step somewhere.

![image](https://github.com/fkretlow/figurato/assets/110628605/fa7d158c-b570-4f8c-8ab5-33d8611ef82b)

**Comment by philipmayr** [comment]
All right so no issue with 7532 using Figurato.otf on Windows. Still doesn't work if I switch over to FiguratoMac.otf, though. I guess 7532 isn't one of the precomposed ligatures. But I'm reading the documentation again and it looks like FiguratoMac is only to be used with Dorico on Macs, if I understand correctly. So maybe I can just download Figurato.otf on my Mac instead.
